apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evdemo.fullname" . }}
  labels:
    {{- include "evdemo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "evdemo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "evdemo.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "evdemo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: IOTICS_HOST_PORT
              value: {{ .Values.publisher.space }}
            - name: USER_SEED_FILE
              value: ".ev-demo.prod.seed"
            - name: AGENT_SEED_FILE
              value: ".ev-demo.prod.seed"
            - name: IOTICS_AK_NAME
              value: "agent-0"
            - name: IOTICS_AGENT_NAME
              value: "tutorial-ev-chargers"
            - name: IOTICS_UK_NAME
              value: "user-tutorial"
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
